# Production version of configurations

#spring:
#  hikari: (important in prod)
#    pool-name: HikariCP # just a label (if you have multiple pools)
#    maximum-pool-size: 5 # max no. of DB connections at once
#    connection-timeout: 10000 # max time (ms) to wait for a free connection
#    idle-timeout: 600000 # Time (ms) a connection can sit unused
#    max-lifetime: 1800000 # max age of a connection (30 mins)
#    validation-timeout: 5000 # max time to wait when checking if a connection is valid (should be in ms)
#    leak-detection-threshold: 0 # detects if a connection isn't returned to pool (0 = disabled)
#    initialization-fail-timeout: -1 # if DB is down at startup, don't fail the app (DB can connect later)


server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        http-only: true

spring:
  application:
    name: auth-app-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # IMPORTANT: No schema mutation in prod
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
              - openid

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user

logging:
  level:
    root: INFO
    org.springframework.security: WARN

security:
  jwt:
    secret: ${JWT_SECRET:PROD_JWT_SECRET_9f3AqLx72H@KpZrT!eM8D1sWvC_EXTRA_RANDOM_1234567890_XYZ} # MUST be set in env
    issuer: ${JWT_ISSUER:auth-app}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: true
    cookie-http-only: true
    cookie-same-site: None
    cookie-domain: ${COOKIE_DOMAIN:}

app:
  cors:
    front-end-url: ${FRONTEND_URL:http://localhost:5173}

  auth:
    frontend:
      success-redirect: ${FRONTEND_URL:http://localhost:5173}/oauth/success
      failure-redirect: ${FRONTEND_URL:http://localhost:5173}/oauth/failure

